### ISSUE TITLE
Loading cartridge JSON's not working locally/online

### ISSUE THREAD

**Issue by henriquelalves** [schteppe/cartridge.js#74]
MACHINE: Linux Mint, Firefox 54.0

EXPECTED: Being able to load cartridges JSON's (from the 'examples' folder) and to see their Sprites, Sounds, and JS code on-editor.

WHAT HAPPENED: Nothing, haha. Everytime I try loading a JSON file on the main tab, Firefox console warns "Could not load file". Offline (on my cloned repo) I was expecting a CrossReference problem, but even the online editor is not loading the JSON's provided.

Maybe I'm missing an editor configuration, but everything was looking correct besides this. I didn't tried a lot of things though, as I intended to learn by example.

BTW, this is an amazing project!

**Comment by henriquelalves** [comment]
Ok, I just solved this by rebuilding both Editor and Engine using `npm all`; is the current build the same as the one that exported the examples?

I'll close this issue if building was a necessary step I missed haha.

**Comment by schteppe** [comment]
Hi, I'm glad to hear you like the project :)
Yes, there was a bug, preventing JSON from loading properly. The bug was fixed, but i had not updated the builds. I've updated them now and pushed them both to main branch and gh-pages. 
The examples were probably exported using an older version of the file format, however the editor should be backwards-compatible so they should work anyway.

**Comment by henriquelalves** [comment]
Great! Everything is working now; I'll be closing this issue.
